version: "3.8"
services:
  redis:
    #镜像及版本
    image: redis:6.2.6
    # 自定义容器名
    container_name: my-redis
    # docker 启动时，自动启动该容器
    restart: always
    # 挂载映射，可以让数据或配置持久化
    volumes:
      # <本地配置文件> : <docker中的配置文件> : <ro:docker容器对该文件只读，默认时rw可读可写>
      - ./redis.conf:/etc/redis/redis.conf
      # <本地数据目录> : <docker中的数据目录>
      - ./data:/data
      # <本地日志目录> : <docker中的日志目录>
      # redis不具有自动创建/logs的权限，如果redis.conf中指定的相对位置,则数据目录已经可以映射出日志文件
      - ./logs:/logs
    # docker执行的启动命令
    command: redis-server /etc/redis/redis.conf
    ports:
      # <本地端口>:<docker容器端口>
      - 6378:6379